<?php

namespace BYanelli\SelfValidatingModels\Tests\TestApp;

use BYanelli\SelfValidatingModels\ModelValidationServiceProvider as BaseServiceProvider;
use Illuminate\Contracts\Validation\Factory;
use Illuminate\Support\Facades\Validator;

class ModelValidationServiceProvider extends BaseServiceProvider
{
    protected $validators = [
        Post::class => PostValidator::class,
    ];

    public function register()
    {
        $factory = $this->app->make(Factory::class);

        $factory->extend('empty', function ($attribute, $value) {
            return empty($value);
        });

        parent::register(); // TODO: Change the autogenerated stub
    }
}
